const crops = [
  { id: 0, name: "Almonds, in shell" },
  { id: 1, name: "Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw" },
  { id: 2, name: "Apples" },
  { id: 3, name: "Apricots" },
  { id: 4, name: "Areca nuts" },
  { id: 5, name: "Artichokes" },
  { id: 6, name: "Asparagus" },
  { id: 7, name: "Avocados" },
  { id: 8, name: "Bananas" },
  { id: 9, name: "Barley" },
  { id: 10, name: "Beans, dry" },
  { id: 11, name: "Broad beans and horse beans, dry" },
  { id: 12, name: "Broad beans and horse beans, green" },
  { id: 13, name: "Buckwheat" },
  { id: 14, name: "Cabbages" },
  { id: 15, name: "Cantaloupes and other melons" },
  { id: 16, name: "Carrots and turnips" },
  { id: 17, name: "Cashew nuts, in shell" },
  { id: 18, name: "Cassava, fresh" },
  { id: 19, name: "Castor oil seeds" },
  { id: 20, name: "Cauliflowers and broccoli" },
  { id: 21, name: "Cereals n.e.c." },
  { id: 22, name: "Cherries" },
  { id: 23, name: "Chestnuts, in shell" },
  { id: 24, name: "Chick peas, dry" },
  { id: 25, name: "Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw" },
  { id: 26, name: "Chillies and peppers, green (Capsicum spp. and Pimenta spp.)" },
  { id: 27, name: "Cinnamon and cinnamon-tree flowers, raw" },
  { id: 28, name: "Cloves (whole stems), raw" },
  { id: 29, name: "Coconuts, in shell" },
  { id: 30, name: "Coffee, green" },
  { id: 31, name: "Cow peas, dry" },
  { id: 32, name: "Cucumbers and gherkins" },
  { id: 33, name: "Dates" },
  { id: 34, name: "Edible roots and tubers with high starch or inulin content, n.e.c., fresh" },
  { id: 35, name: "Eggplants (aubergines)" },
  { id: 36, name: "Figs" },
  { id: 37, name: "Flax, processed but not spun" },
  { id: 38, name: "Ginger, raw" },
  { id: 39, name: "Grapes" },
  { id: 40, name: "Green corn (maize)" },
  { id: 41, name: "Green garlic" },
  { id: 42, name: "Groundnuts, excluding shelled" },
  { id: 43, name: "Hazelnuts, in shell" },
  { id: 44, name: "Hop cones" },
  { id: 45, name: "Jute, raw or retted" },
  { id: 46, name: "Kenaf, and other textile bast fibres, raw or retted" },
  { id: 47, name: "Kiwi fruit" },
  { id: 48, name: "Leeks and other alliaceous vegetables" },
  { id: 49, name: "Lemons and limes" },
  { id: 50, name: "Lentils, dry" },
  { id: 51, name: "Lettuce and chicory" },
  { id: 52, name: "Linseed" },
  { id: 53, name: "Maize (corn)" },
  { id: 54, name: "Mangoes, guavas and mangosteens" },
  { id: 55, name: "Melonseed" },
  { id: 56, name: "Millet" },
  { id: 57, name: "Mustard seed" },
  { id: 58, name: "Natural rubber in primary forms" },
  { id: 59, name: "Oats" },
  { id: 60, name: "Oil palm fruit" },
  { id: 61, name: "Olives" },
  { id: 62, name: "Onions and shallots, dry (excluding dehydrated)" },
  { id: 63, name: "Onions and shallots, green" },
  { id: 64, name: "Oranges" },
  { id: 65, name: "Other beans, green" },
  { id: 66, name: "Other berries and fruits of the genus vaccinium n.e.c." },
  { id: 67, name: "Other citrus fruit, n.e.c." },
  { id: 68, name: "Other fibre crops, raw, n.e.c." },
  { id: 69, name: "Other fruits, n.e.c." },
  { id: 70, name: "Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c." },
  { id: 71, name: "Other oil seeds, n.e.c." },
  { id: 72, name: "Other pulses n.e.c." },
  { id: 73, name: "Other stimulant, spice and aromatic crops, n.e.c." },
  { id: 74, name: "Other stone fruits" },
  { id: 75, name: "Other tropical fruits, n.e.c." },
  { id: 76, name: "Other vegetables, fresh n.e.c." },
  { id: 77, name: "Papayas" },
  { id: 78, name: "Peaches and nectarines" },
  { id: 79, name: "Pears" },
  { id: 80, name: "Peas, dry" },
  { id: 81, name: "Peas, green" },
  { id: 82, name: "Pepper (Piper spp.), raw" },
  { id: 83, name: "Persimmons" },
  { id: 84, name: "Pineapples" },
  { id: 85, name: "Pistachios, in shell" },
  { id: 86, name: "Plums and sloes" },
  { id: 87, name: "Pomelos and grapefruits" },
  { id: 88, name: "Potatoes" },
  { id: 89, name: "Pumpkins, squash and gourds" },
  { id: 90, name: "Quinces" },
  { id: 91, name: "Ramie, raw or retted" },
  { id: 92, name: "Rape or colza seed" },
  { id: 93, name: "Rice" },
  { id: 94, name: "Rye" },
  { id: 95, name: "Safflower seed" },
  { id: 96, name: "Seed cotton, unginned" },
  { id: 97, name: "Sesame seed" },
  { id: 98, name: "Sisal, raw" },
  { id: 99, name: "Sorghum" },
  { id: 100, name: "Soya beans" },
  { id: 101, name: "Spinach" },
  { id: 102, name: "Strawberries" },
  { id: 103, name: "String beans" },
  { id: 104, name: "Sugar beet" },
  { id: 105, name: "Sugar cane" },
  { id: 106, name: "Sunflower seed" },
  { id: 107, name: "Sweet potatoes" },
  { id: 108, name: "Tallowtree seeds" },
  { id: 109, name: "Tangerines, mandarins, clementines" },
  { id: 110, name: "Taro" },
  { id: 111, name: "Tea leaves" },
  { id: 112, name: "Tomatoes" },
  { id: 113, name: "Triticale" },
  { id: 114, name: "True hemp, raw or retted" },
  { id: 115, name: "Tung nuts" },
  { id: 116, name: "Unmanufactured tobacco" },
  { id: 117, name: "Vanilla, raw" },
  { id: 118, name: "Vegetables, n.e.c." },
  { id: 119, name: "Walnuts, in shell" },
  { id: 120, name: "Watermelons" },
  { id: 121, name: "Wheat" },
  { id: 122, name: "Yams" },
  { id: 123, name: "Zucchini" },
  { id: 124, name: "Pigeon peas, dry" },
  { id: 125, name: "Currants" },
  { id: 126, name: "Gooseberries" },
  { id: 127, name: "Mixed grain" },
  { id: 128, name: "Raspberries" },
  { id: 129, name: "Blueberries" },
  { id: 130, name: "Cranberries" },
  { id: 131, name: "Sour cherries" }
];

export default crops;
